name: Release linux

on: [workflow_dispatch]
jobs:
  build_uif:
    name: Build and Release
    runs-on: macos-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v5
        with:
          go-version: "1.21"
      - uses: actions/setup-node@v3
        with:
          node-version: "22.2.0"

      - run: npm install --force

      - name: Build Web
        env:
          NODE_OPTIONS: "--openssl-legacy-provider"
        run: npm run build:stage
        
      - run: cp -R ./dist/ ./uifd/web_dist/

      - uses: goreleaser/goreleaser-action@v4
        with:
          install-only: true
          version: "v1.26.2"

      - run: |
          git tag -a manual_`TZ=Asia/Shanghai date +"%Y%m%d_%H_%M_%S"` -m "release by manual"
          cd uifd/service/
          goreleaser --snapshot --clean
          cd ..
          go build -o build.exe ./build_service
          ./build.exe
          ls
          goreleaser --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          echo "ui4freedom.org" >> ./dist/CNAME
          mkdir ./dist/releases/
          cp ./uifd/dist/uif-* ./dist/releases/
          cp ./uifd/dist/uif-* ./doc/static/assets/release/
          cp ./uifd/ui4freedom* ./doc/static/assets/release/
          cp ./uifd/uiforfreedom* ./doc/static/assets/release/
          cp ./uifd/linux_install.sh ./doc/static/assets/release/
          cp ./uifd/version/* ./doc/static/assets/release/version

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release_cache
          path: ./doc/static/assets/release/


